In [2]:
import pandas as pd
import requests
import json

pd.set_option('display.max_columns', None)

In [3]:
url = "https://api.pluggy.ai/auth"

payload = {
    "clientId": "e3092229-0226-4439-b5b5-535a16dfeb42",
    "clientSecret": "TnzAyRxru9rTdoLOjQIePsoCTPJsAnPwXZFGwxAapbw"
}

headers = {
    "accept": "application/json",
    "content-type": "application/json"
}

api_key = requests.post(url,json=payload, headers=headers).json().get("apiKey")

In [4]:
print(f"API Key: {api_key}")

API Key: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMmM2ZWFjMTRmYTRlOTgwOGM2YTQ1MjljODhmZjcyZTQ6YmMyNzI1MmE0OWYxZGE2OTJhMGJjZmU3YjdjZWU4YWQ4NjA4NmZjOTU4NWFiNjZiMjhkNjI2OWY5MDQ1MDdhMGNiNmFhOWNhZWY4ZGQzZjk0OGE0ZDM4OTFkMzlkYjdiZGY1Y2QxMzI1Mjk4Y2E1MDM2ZTVjMWQ4MWIyMjhjOGU1Yjk0MDhlYjNmMmIxNTYxMGE3YzkwZmI2YTkwNzQzMCIsImlhdCI6MTc4OTMzNjIyMywiZXhwIjoxNzg5MzQzNDIzfQ.ssCs4Ysb2FcBLeZss2ufp-cLEL65vlndSE8DVYmH4UloZkFq8HLz-BR_Z-Aj19gpOtH-JOpa0p7ovjz8ZHiku4QMuXo-G2WBQwxviU0bLyBvMx-JfeFgd2VwqHBitKzCfTveTzoHQkZfhy80XvgwXPMM-WLeHsphEcO4hyKlD_pkMlDG2H8kQgXNXnB0Z18hLVUscjyvB3hniuSvkjtG8wl7ZrOhtSEL0lyJHKZYsC1U_zL3NUZbrH_FSiXlOjta2nnoRYhNgMMTYDlXnipDVhX5FKi8mdZe4oSeMva39ewUY1cWsJvrD-us2fuUJZYaRK6KoBivl0C_LaY_dJXuKA

In [5]:
headers = {
    "X-API-KEY": api_key,
    "Content-Type": "application/json"
}

url = "https://api.pluggy.ai/v2/transactions"

response = requests.get(url, headers=headers, json=payload,  params={"accountId": "f371a714-16ea-4bb4-b3c6-24381eac1642"}).json().get("results")

In [6]:
print(response)

[{'id': '5cba03cd-c12c-4353-9f54-a120931aac1f', 'description': 'Pastel Do Henrique', 'descriptionRaw': 'Pastel Do Henrique', 'currencyCode': 'BRL', 'amount': 21, 'amountInAccountCurrency': None, 'date': '2026-09-12T14:52:54.411Z', 'category': 'Eating out', 'categoryId': '11010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5499, 'billForecastDate': '2026-10'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '4b840162-da61-413f-9643-37c7ecffd38e', 'description': 'Wellhub Matheus Rocha', 'descriptionRaw': 'Wellhub Matheus Rocha', 'currencyCode': 'BRL', 'amount': 80, 'amountInAccountCurrency': None, 'date': '2026-09-10T16:36:38.361Z', 'category': 'Digital services', 'categoryId': '09000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5968, 'billForecastDate': '2026-10'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '9c461a45-a013-4802-b22c-af984d36884b', 'description': 'Enel', 'descriptionRaw': 'Enel', 'currencyCode': 'BRL', 'amount': 108.75, 'amountInAccountCurrency': None, 'date': '2026-09-08T22:05:29.771Z', 'category': 'Utilities', 'categoryId': '17020000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 4900, 'billForecastDate': '2026-10'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'f03544c9-2188-43e5-b376-008fa07e9379', 'description': 'Claro', 'descriptionRaw': 'Claro', 'currencyCode': 'BRL', 'amount': 242.7, 'amountInAccountCurrency': None, 'date': '2026-09-08T22:03:55.665Z', 'category': 'Telecommunications', 'categoryId': '07010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 4814, 'billForecastDate': '2026-10'}, 'merchant': {'cnae': '6120501', 'cnpj': '40432544000147', 'category': 'Mobile', 'businessName': 'CLARO S.A.'}, 'providerId': None, 'order': 1, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '0ca6cb7b-4f53-4307-bb58-d15ccf8124bc', 'description': 'QuintoAndar', 'descriptionRaw': 'QuintoAndar', 'currencyCode': 'BRL', 'amount': 2215.58, 'amountInAccountCurrency': None, 'date': '2026-09-08T22:02:18.787Z', 'category': 'Rent', 'categoryId': '17010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 6513, 'billForecastDate': '2026-10'}, 'merchant': {'cnpj': '', 'name': 'quintoandar', 'businessName': ''}, 'providerId': None, 'order': 2, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '19e97f91-e1fb-4193-8e0e-419add8a97e5', 'description': 'Adobe Adobe', 'descriptionRaw': 'Adobe Adobe', 'currencyCode': 'BRL', 'amount': 55, 'amountInAccountCurrency': None, 'date': '2026-09-04T19:02:24.297Z', 'category': 'Digital services', 'categoryId': '09000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 4816, 'billForecastDate': '2026-10'}, 'merchant': {'cnae': '6204000', 'cnpj': '02999520000185', 'category': 'Services', 'businessName': 'ADOBE SYSTEMS BRASIL LTDA.'}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'a35a2403-e6a4-41fd-81c8-a0d73be7a131', 'description': 'Mongeral', 'descriptionRaw': 'Mongeral', 'currencyCode': 'BRL', 'amount': 360.89, 'amountInAccountCurrency': None, 'date': '2026-09-03T07:32:14.378Z', 'category': 'Insurance', 'categoryId': '20000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 6300, 'billForecastDate': '2026-10'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '97609228-64ce-447a-9929-642df9661a22', 'description': 'Pagamento', 'descriptionRaw': 'Pagamento', 'currencyCode': 'BRL', 'amount': -6476.11, 'amountInAccountCurrency': None, 'date': '2026-09-01T12:44:21.339Z', 'category': 'Credit card payment', 'categoryId': '05100000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'PENDING', 'paymentData': None, 'type': 'CREDIT', 'operationType': 'PAGAMENTO_FATURA', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '6194', 'billForecastDate': '2026-10'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'd33cdac6-44cf-4362-9452-5ca7298b275b', 'description': 'Posto Estrela Da Dutra', 'descriptionRaw': 'Posto Estrela Da Dutra', 'currencyCode': 'BRL', 'amount': 156.85, 'amountInAccountCurrency': None, 'date': '2026-08-31T12:21:42.546Z', 'category': 'Gas stations', 'categoryId': '19050001', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5541, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'f3e5105a-5883-41fa-b417-d0863f9f8f2b', 'description': 'Rei Da Villa', 'descriptionRaw': 'Rei Da Villa', 'currencyCode': 'BRL', 'amount': 90.2, 'amountInAccountCurrency': None, 'date': '2026-08-30T22:22:55.382Z', 'category': 'Eating out', 'categoryId': '11010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5814, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '3b1d47e6-a864-4b07-99d8-89cb08a24585', 'description': 'Farmacia C Comercial', 'descriptionRaw': 'Farmacia C Comercial', 'currencyCode': 'BRL', 'amount': 44.5, 'amountInAccountCurrency': None, 'date': '2026-08-30T21:38:52.119Z', 'category': 'Pharmacy', 'categoryId': '18020000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5912, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '6f54c8b9-8496-4073-a688-787336670973', 'description': 'Parquetur Itatiaia Sa', 'descriptionRaw': 'Parquetur Itatiaia Sa', 'currencyCode': 'BRL', 'amount': 8, 'amountInAccountCurrency': None, 'date': '2026-08-30T18:06:18.710Z', 'category': 'Leisure', 'categoryId': '21000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7996, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 2, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'e49fcce3-2c39-46f1-a265-fe6cc432edc9', 'description': 'Pousada Coracoes', 'descriptionRaw': 'Pousada Coracoes', 'currencyCode': 'BRL', 'amount': 225, 'amountInAccountCurrency': None, 'date': '2026-08-30T01:04:08.185Z', 'category': 'Accomodation', 'categoryId': '12020000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7011, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 3, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'd542ecca-a843-4e60-b4bd-c6bfead12dad', 'description': 'Droga Aurea', 'descriptionRaw': 'Droga Aurea', 'currencyCode': 'BRL', 'amount': 15.04, 'amountInAccountCurrency': None, 'date': '2026-08-29T21:22:20.296Z', 'category': 'Pharmacy', 'categoryId': '18020000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5912, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'cc76eabc-4808-4040-981e-36bd9958b300', 'description': 'Abastece Aí', 'descriptionRaw': 'Abastece Aí', 'currencyCode': 'BRL', 'amount': 209.76, 'amountInAccountCurrency': None, 'date': '2026-08-29T18:32:40.737Z', 'category': 'Gas stations', 'categoryId': '19050001', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5541, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'c1212ee8-2d3f-4561-814c-bb79ac4e9010', 'description': 'Playball', 'descriptionRaw': 'Playball', 'currencyCode': 'BRL', 'amount': 20, 'amountInAccountCurrency': None, 'date': '2026-08-29T16:02:45.205Z', 'category': 'Leisure', 'categoryId': '21000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7999, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 2, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '89b08d26-e2c4-4474-9a00-ea053f1ee748', 'description': 'Playball', 'descriptionRaw': 'Playball', 'currencyCode': 'BRL', 'amount': 21, 'amountInAccountCurrency': None, 'date': '2026-08-29T16:02:14.130Z', 'category': 'Leisure', 'categoryId': '21000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7999, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 3, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'a5031159-7d17-4fc8-b8e8-bde84a622b5b', 'description': 'Lojas Americanas', 'descriptionRaw': 'Lojas Americanas', 'currencyCode': 'BRL', 'amount': 3.98, 'amountInAccountCurrency': None, 'date': '2026-08-28T16:01:18.617Z', 'category': 'Food and drinks', 'categoryId': '11000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5311, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': {'cnae': '4711302', 'cnpj': '33014556000196', 'category': 'Food and drinks', 'businessName': 'LOJAS AMERICANAS S.A.'}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '3bf53623-b92b-4ec8-8e03-96387afdb25e', 'description': '99', 'descriptionRaw': '99', 'currencyCode': 'BRL', 'amount': 10.39, 'amountInAccountCurrency': None, 'date': '2026-08-28T00:41:11.910Z', 'category': 'Taxi and ride-hailing', 'categoryId': '19010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 4121, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'c294cf69-5c3b-41e6-b94c-2caccff5562f', 'description': 'Parquetur Itatiaia Sa', 'descriptionRaw': 'Parquetur Itatiaia Sa', 'currencyCode': 'BRL', 'amount': 59, 'amountInAccountCurrency': None, 'date': '2026-08-27T18:04:30.968Z', 'category': 'Leisure', 'categoryId': '21000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7996, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': 'ae6aa94d-c6b0-47ee-a8f2-22903310ff82', 'description': 'Pousada 3 Corações Pen', 'descriptionRaw': 'Pousada 3 Corações Pen', 'currencyCode': 'BRL', 'amount': 225, 'amountInAccountCurrency': None, 'date': '2026-08-27T17:45:56.421Z', 'category': 'Accomodation', 'categoryId': '12020000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7011, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 1, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '9dcf1fe5-68d3-43a4-af53-2f7649e11992', 'description': 'Wikilo', 'descriptionRaw': 'Wikilo', 'currencyCode': 'BRL', 'amount': 38.95, 'amountInAccountCurrency': None, 'date': '2026-08-25T23:53:51.291Z', 'category': 'Digital services', 'categoryId': '09000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5815, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': None, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '581c8a0d-84b5-4f9f-8149-0b8fe6ca628a', 'description': 'Mercado Livre', 'descriptionRaw': 'Mercado Livre', 'currencyCode': 'BRL', 'amount': 78.99, 'amountInAccountCurrency': None, 'date': '2026-08-23T14:19:56.556Z', 'category': 'Investments', 'categoryId': '03000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 5310, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': {'cnae': '6463800', 'cnpj': '03361252000134', 'category': 'Investments', 'businessName': 'MERCADOLIVRE.COM ATIVIDADES DE INTERNET LTDA'}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '93c08d60-26c8-4587-800b-57babbc015da', 'description': 'Aliexpress', 'descriptionRaw': 'Aliexpress', 'currencyCode': 'BRL', 'amount': 113.72, 'amountInAccountCurrency': None, 'date': '2026-08-22T01:54:45.911Z', 'category': 'Online shopping', 'categoryId': '08010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7372, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': {'cnpj': '', 'name': 'AliExpress', 'businessName': ''}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '84be07a2-9233-4670-8a81-35012811b17c', 'description': 'Aliexpress', 'descriptionRaw': 'Aliexpress', 'currencyCode': 'BRL', 'amount': 693.29, 'amountInAccountCurrency': None, 'date': '2026-08-21T02:46:44.464Z', 'category': 'Online shopping', 'categoryId': '08010000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': '0512', 'payeeMCC': 7372, 'billId': '3f2641c2-8f66-44ad-8e41-7d920607eb3d', 'billForecastDate': '2026-09'}, 'merchant': {'cnpj': '', 'name': 'AliExpress', 'businessName': ''}, 'providerId': None, 'order': 0, 'createdAt': '2026-09-13T02:28:32.336Z', 'updatedAt': '2026-09-13T02:28:32.336Z'}, {'id': '1d94809c-e9f2-4d86-bd3f-46e3619be0c9', 'description': 'Vfy Comercio Locacao', 'descriptionRaw': 'Vfy Comercio Locacao', 'currencyCode': 'BRL', 'amount': 7.39, 'amountInAccountCurrency': None, 'date': '2026-08-19T15:32:54.936Z', 'category': 'Groceries', 'categoryId': '10000000', 'balance': None, 'accountId': 'f371a714-16ea-4bb4-b3c6-24381eac1642', 'providerCode': None, 'status': 'POSTED', 'paymentData': None, 'type': 'DEBIT', 'operationType': 'PAGAMENTO', 'operationTypeAdditionalInfo': None, 'creditCardMetadata': {'cardNumber': 

In [7]:
transactions_raw = pd.DataFrame([
    {chave: valor for chave, valor in item.items()}
    for item in response
])

transactions_raw.head(5)

,id,description,descriptionRaw,currencyCode,amount,amountInAccountCurrency,date,category,categoryId,balance,accountId,providerCode,status,paymentData,type,operationType,operationTypeAdditionalInfo,creditCardMetadata,merchant,providerId,order,createdAt,updatedAt
0,5cba03cd-c12c-4353-9f54-a120931aac1f,Pastel Do Henrique,Pastel Do Henrique,BRL,21.00,None,2026-09-12T14:52:54.411Z,Eating out,11010000,None,f371a714-16ea-4bb4-b3c6-24381eac1642,None,PENDING,None,DEBIT,PAGAMENTO,None,"{'cardNumber': '0512', 'payeeMCC': 5499, 'bill...",None,None,0,2026-09-13T02:28:32.336Z,2026-09-13T02:28:32.336Z
1,4b840162-da61-413f-9643-37c7ecffd38e,Wellhub Matheus Rocha,Wellhub Matheus Rocha,BRL,80.00,None,2026-09-10T16:36:38.361Z,Digital services,09000000,None,f371a714-16ea-4bb4-b3c6-24381eac1642,None,PENDING,None,DEBIT,PAGAMENTO,None,"{'cardNumber': '0512', 'payeeMCC': 5968, 'bill...",None,None,0,2026-09-13T02:28:32.336Z,2026-09-13T02:28:32.336Z
2,9c461a45-a013-4802-b22c-af984d36884b,Enel,Enel,BRL,108.75,None,2026-09-08T22:05:29.771Z,Utilities,17020000,None,f371a714-16ea-4bb4-b3c6-24381eac1642,None,PENDING,None,DEBIT,PAGAMENTO,None,"{'cardNumber': '0512', 'payeeMCC': 4900, 'bill...",None,None,0,2026-09-13T02:28:32.336Z,2026-09-13T02:28:32.336Z
3,f03544c9-2188-43e5-b376-008fa07e9379,Claro,Claro,BRL,242.70,None,2026-09-08T22:03:55.665Z,Telecommunications,07010000,None,f371a714-16ea-4bb4-b3c6-24381eac1642,None,PENDING,None,DEBIT,PAGAMENTO,None,"{'cardNumber': '0512', 'payeeMCC': 4814, 'bill...","{'cnae': '6120501', 'cnpj': '40432544000147', ...",None,1,2026-09-13T02:28:32.336Z,2026-09-13T02:28:32.336Z
4,0ca6cb7b-4f53-4307-bb58-d15ccf8124bc,QuintoAndar,QuintoAndar,BRL,2215.58,None,2026-09-08T22:02:18.787Z,Rent,17010000,None,f371a714-16ea-4bb4-b3c6-24381eac1642,None,PENDING,None,DEBIT,PAGAMENTO,None,"{'cardNumber': '0512', 'payeeMCC': 6513, 'bill...","{'cnpj': '', 'name': 'quintoandar', 'businessN...",None,2,2026-09-13T02:28:32.336Z,2026-09-13T02:28:32.336Z

In [8]:
transactions = transactions_raw[['id', 'description', 'amount', 'currencyCode', 'date', 'category', 'type', 'status', 'operationType', 'createdAt']]
# transactions['bankName'] = 'NuBank'
transactions.head()

,id,description,amount,currencyCode,date,category,type,status,operationType,createdAt
0,5cba03cd-c12c-4353-9f54-a120931aac1f,Pastel Do Henrique,21.00,BRL,2026-09-12T14:52:54.411Z,Eating out,DEBIT,PENDING,PAGAMENTO,2026-09-13T02:28:32.336Z
1,4b840162-da61-413f-9643-37c7ecffd38e,Wellhub Matheus Rocha,80.00,BRL,2026-09-10T16:36:38.361Z,Digital services,DEBIT,PENDING,PAGAMENTO,2026-09-13T02:28:32.336Z
2,9c461a45-a013-4802-b22c-af984d36884b,Enel,108.75,BRL,2026-09-08T22:05:29.771Z,Utilities,DEBIT,PENDING,PAGAMENTO,2026-09-13T02:28:32.336Z
3,f03544c9-2188-43e5-b376-008fa07e9379,Claro,242.70,BRL,2026-09-08T22:03:55.665Z,Telecommunications,DEBIT,PENDING,PAGAMENTO,2026-09-13T02:28:32.336Z
4,0ca6cb7b-4f53-4307-bb58-d15ccf8124bc,QuintoAndar,2215.58,BRL,2026-09-08T22:02:18.787Z,Rent,DEBIT,PENDING,PAGAMENTO,2026-09-13T02:28:32.336Z

In [9]:
transactions.loc[transactions['description'].str.contains('Spotify', case=False, na=False)]

,id,description,amount,currencyCode,date,category,type,status,operationType,createdAt
45,aa02831d-9b59-4ef2-a7ca-a6fc830fcc26,Spotify,23.9,BRL,2026-07-27T15:47:18.562Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
77,a63c0520-da84-4893-b771-dcc786997cec,Spotify,23.9,BRL,2026-06-27T15:47:21.387Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
116,5cd7d09d-11c3-45ce-8ae9-854096267640,Spotify,23.9,BRL,2026-05-27T15:47:21.673Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
155,aac8a5aa-fed6-4f5d-a78c-87728d5239ec,Spotify,23.9,BRL,2026-04-27T15:47:20.700Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
180,55cae9d7-f221-4641-9587-6ffdb81e4d3a,Spotify,23.9,BRL,2026-03-27T15:47:19.764Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
205,40b1d981-4d07-4a4a-830a-31691f903c6d,Spotify,23.9,BRL,2026-02-27T15:47:20.999Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
228,4cc6070d-7f77-4e3b-8400-05de8516bccb,EBN*SPOTIFYCURITIBABRA,23.9,BRL,2026-01-27T15:47:25.773Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
263,dac28a23-11b8-4022-910f-b1a12f1480a5,EBN*SPOTIFYCURITIBABRA,23.9,BRL,2025-12-27T15:47:21.275Z,Music streaming,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
286,e500b578-ee03-41f9-becd-08db1e03f27c,EBN *SPOTIFYCURITIBABRA,23.9,BRL,2025-11-27T15:47:21.623Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
353,0ca64ce4-8fc3-4f8c-868b-bf38011b0b9d,EBN*SPOTIFYCURITIBABRA,23.9,BRL,2025-10-27T15:47:11.929Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z
388,abb0d199-5eca-4d8a-9cb7-8024334de604,EBN *SPOTIFYCURITIBABRA,23.9,BRL,2025-09-14T18:01:03.553Z,Digital services,DEBIT,POSTED,PAGAMENTO,2026-09-13T02:28:32.336Z

In [6]:
merchants = pd.json_normalize(transactions_raw.loc[~transactions_raw['merchant'].isnull()][['merchant']].drop_duplicates()['merchant'])
merchants = merchants.rename(columns={'category': 'merchantCategory', 'cnae': 'merchantCnae', 'cnpj': 'merchantCnpj', 'id': 'merchantId', 'businessName': 'merchantName'})

merchants.head(5)

,merchantCnae,merchantCnpj,merchantCategory,merchantName
2,4761001,15436940000103,Bookstore,AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.
12,9430800,29258597000231,Services,UNIAO NACIONAL DOS ESTUDANTES
14,7490104,25021356000132,Services,DLOCAL BRASIL INSTITUICAO DE PAGAMENTO S.A.
20,6493000,48041735000190,Services,PORTO SEGURO ADMINISTRADORA DE CONSORCIOS LTDA
23,8112500,18328750000152,Housing,CONDOMINIO LIBER BOSQUE DOS BURITIS

In [7]:
transactions_final = transactions.join(merchants, how='left')
transactions_final.head(5)

,id,description,amount,currencyCode,date,category,type,status,operationType,createdAt,bankName,merchantCnae,merchantCnpj,merchantCategory,merchantName
0,d8ae8028-9d5a-49b7-859e-0c29997f7e1a,Aplicação RDB,-9507.15,BRL,2026-07-19T15:20:23.854Z,Investments,DEBIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN
1,ede79446-850f-4fc5-bc11-80726139db1f,Transferência Recebida|Matheus Rocha Cardoso,9507.15,BRL,2026-07-19T15:19:41.213Z,Same person transfer,CREDIT,POSTED,PIX,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN
2,df93e824-25ab-4f72-b47e-45248ed1adc7,Transferência enviada|Amazon Serviços de Varej...,-563.32,BRL,2026-07-12T18:22:20.474Z,Bookstore,DEBIT,POSTED,PIX,2026-09-07T20:32:23.537Z,NuBank,4761001,15436940000103,Bookstore,AMAZON SERVICOS DE VAREJO DO BRASIL LTDA.
3,8c2e86c6-22f7-4c2b-9068-fc4f7c70a87c,Resgate RDB,563.32,BRL,2026-07-12T18:21:52.056Z,Investments,CREDIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN
4,24f69692-b2ae-4438-96b0-f1f0a2e5cb94,Aplicação RDB,-12509.35,BRL,2026-07-01T11:35:45.759Z,Investments,DEBIT,POSTED,RESGATE_APLIC_FINANCEIRA,2026-09-07T20:32:23.537Z,NuBank,NaN,NaN,NaN,NaN

In [8]:
transactions_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                48 non-null     str
 1   description       48 non-null     str
 2   amount            48 non-null     float64
 3   currencyCode      48 non-null     str
 4   date              48 non-null     str
 5   category          48 non-null     str
 6   type              48 non-null     str
 7   status            48 non-null     str
 8   operationType     48 non-null     str
 9   createdAt         48 non-null     str
 10  bankName          48 non-null     str
 11  merchantCnae      8 non-null      str
 12  merchantCnpj      8 non-null      str
 13  merchantCategory  8 non-null      str
 14  merchantName      8 non-null      str
dtypes: float64(1), str(14)
memory usage: 5.8 KB

In [9]:
transactions.to_csv('transactions.csv', index=False)